language: ruby
sudo: false
os:
- linux
- osx
branches:
except:
- gh-pages
- next_doc_release
env:
- secure: "d/fE2Iuyrf5mfvQPe2nl++a06hpy82mEM5jbmXmS1ttQgMpf955GWTmZ+16VBZa9MU2pJLBXoBXy53tp8P9ADysE4R7YCeI68yE0CZ/OuU+FVADZ9/F6i4nlUESjNNQnlC0mTIjDMO5WI9HbVQiS07HqDHzr6bcS51ZvBzItcn4="
rvm:
- jruby-19mode
before_install:
- gem update --system
- gem update bundler
script: rake ci

